### PR TITLE
super_beginners_guide.md delete

### PR DESCRIPTION
**Pull request by wannahappyaroundme**
delete super_beginners_guide.md

### CODE REVIEW

**Review by soulee-dev — CHANGES_REQUESTED** [review]
주석처리가 아닌, 파일 삭제 진행해주셔도 좋을거 같습니다!

**Comment by wannahappyaroundme** [comment]
delete super_beginner_gudie.md

**Comment by wannahappyaroundme** [comment]
delete all source

**Review by soulee-dev — APPROVED** [review]
LGTM

**Comment by wannahappyaroundme** [comment]
request approve

**Pull request merged**
